version: "3.7"

services:
  influx:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=tautulli
      - DOCKER_INFLUXDB_INIT_PASSWORD=tautulli
      - DOCKER_INFLUXDB_INIT_ORG=arrexporter
      - DOCKER_INFLUXDB_INIT_BUCKET=arrexporter
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    restart: unless-stopped

  arrexporter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arrexporter
    environment:
      - INFLUX_URL=http://influx:8086
      - INFLUX_TOKEN=my-super-secret-auth-token
      - INFLUX_ORG=arrexporter
      - INFLUX_BUCKET=arrexporter

      - TAUTULLI_ENABLED=false
      - TAUTULLI_URL=
      - TAUTULLI_API_KEY=

      - RADARR_ENABLED=false
      - RADARR_URL=
      - RADARR_API_KEY=
    depends_on:
      - influx
    restart: unless-stopped