name: Create and publish a Docker image

on:
  release:
    types:
      - created

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5.9
        with:
          registry: ghcr.io
          image: ${{ github.event.repository.name }}
          addLatest: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
